Fixes #14
Workaround für massenhafte Bluetooth Fehlermeldungen in den Syslogs

diff --git a/daemon/daemon b/daemon/daemon
--- a/daemon/daemon
+++ b/daemon/daemon
@@ -1,7 +1,7 @@
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          BLE-Scanner
-# Required-Start:    $remote_fs $syslog $network 
+# Required-Start:    $remote_fs $syslog $network
 # Required-Stop:     $remote_fs $syslog $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
@@ -21,74 +21,85 @@ PATH=$PATH.":REPLACEBYBASEFOLDER/sbin"
 
 case "${1:-''}" in
   'stop')
-				pkill -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php"
-				if [ $? -eq 1 ] 
-				then
-					# Exit with Status 1
+        pkill -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php"
+        if [ $? -eq 1 ]
+        then
+          # Exit with Status 1
           log_failure_msg "BLE-Scanner daemon not running"
-				else
+        else
           log_daemon_msg "BLE-Scanner daemon stopped" "OK"
-        	log_end_msg 0
-				fi
+          log_end_msg 0
+        fi
         exit 0
         ;;
   'status')
-				output=$( pgrep -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php" )
-				if [ $? -eq 1 ] 
-				then
+        output=$( pgrep -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php" )
+        if [ $? -eq 1 ]
+        then
           log_action_msg "Not running"
-				else
-	        log_action_msg "Running with PID `echo -n $output`"
-				fi
+        else
+          log_action_msg "Running with PID `echo -n $output`"
+        fi
         exit 0
         ;;
-	  *)
-  			output=$( pgrep -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php" )
-				if [ $? -eq 1 ] 
-				then
-	        # Start daemon
-	        log_action_msg "Try to start BLE-Scanner daemon"
-	        # Now start the daemon
-						if [ -x /bin/hciconfig ]
-						then
-							/bin/hciconfig hci0 up
-							if [ $? -eq 1 ] 
-							then
-			          log_failure_msg "Error during start of bluetooth interface hci0 - please check"
-			        	exit 1
-							else
-								if [ -x /usr/bin/php ]
-								then
-				        	if [ -x /usr/bin/python ]
-				          then
-				            output=$( /usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php >/dev/null 2>&1 & )
-										output=$( pgrep -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php" )
-										if [ $? -eq 1 ] 
-										then
-						          log_failure_msg "BLE-Scanner Daemon NOT started" 
-						        	exit 1
-										else
-						          log_daemon_msg "BLE-Scanner Daemon started" "OK"
-						          log_end_msg 0
-						        	exit 0
-										fi
-				           else
-				            log_failure_msg "Python not found"
-					        	exit 1
-				           fi
-								else
-				          log_failure_msg "PHP not found"
-				        	exit 1
-								fi
-							fi
-						else
-							log_failure_msg "Starting Bluetooth interface using 'hciconfig' failed"
-		        	exit 1
-						fi
-				else
-	        log_failure_msg "Already running with PID `echo -n $output` - please use stop first"
-        	exit 1
+    *)
+        if [ -r /etc/rsyslog.d/99-BLE-Scanner.conf ]
+        then
+          log_daemon_msg "Update remove syslog errors rule but not restarting syslog" "OK\n"
+          echo ':msg,contains,"advertising data length corrected" ~' > /etc/rsyslog.d/99-BLE-Scanner.conf
+          echo ':msg,contains,"bt_err_ratelimited:" ~'              >> /etc/rsyslog.d/99-BLE-Scanner.conf
+        else
+          log_daemon_msg "Create remove syslog errors rule + restart syslog" "OK\n"
+          echo ':msg,contains,"advertising data length corrected" ~' > /etc/rsyslog.d/99-BLE-Scanner.conf
+          echo ':msg,contains,"bt_err_ratelimited:" ~'              >> /etc/rsyslog.d/99-BLE-Scanner.conf
+          service rsyslog restart
         fi
-        exit 1				
+        output=$( pgrep -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php" )
+        if [ $? -eq 1 ]
+        then
+          # Start daemon
+          log_action_msg "Try to start BLE-Scanner daemon"
+          # Now start the daemon
+            if [ -x /bin/hciconfig ]
+            then
+              /bin/hciconfig hci0 up
+              if [ $? -eq 1 ]
+              then
+                log_failure_msg "Error during start of bluetooth interface hci0 - please check"
+                exit 1
+              else
+                if [ -x /usr/bin/php ]
+                then
+                  if [ -x /usr/bin/python ]
+                  then
+                    output=$( /usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php >/dev/null 2>&1 & )
+                    output=$( pgrep -f "/usr/bin/php -f REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/daemon.php" )
+                    if [ $? -eq 1 ]
+                    then
+                      log_failure_msg "BLE-Scanner Daemon NOT started"
+                      exit 1
+                    else
+                      log_daemon_msg "BLE-Scanner Daemon started" "OK"
+                      log_end_msg 0
+                      exit 0
+                    fi
+                   else
+                    log_failure_msg "Python not found"
+                    exit 1
+                   fi
+                else
+                  log_failure_msg "PHP not found"
+                  exit 1
+                fi
+              fi
+            else
+              log_failure_msg "Starting Bluetooth interface using 'hciconfig' failed"
+              exit 1
+            fi
+        else
+          log_failure_msg "Already running with PID `echo -n $output` - please use stop first"
+          exit 1
+        fi
+        exit 1
         ;;
 esac
